In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
df = pd.read_csv('/Users/noahgomez/GitHub/Analytics-Portfolio/stackoverflow_analysis/data/raw/posts_users_join.csv')

In [8]:
print(df.head())

         id                                              title  \
0  52474162                  Why is SerialGC chosen over G1GC?
1  21775198     Facebook API "This app is in development mode"
2  20900218                  How to debug @font-face problems?
3  43467095  Why is a const variable sometimes not required...
4  61255807       Coroutine scope on Application class android

                      creation_date                last_activity_date  \
0  2018-09-24 07:03:09.697000+00:00  2022-05-01 15:01:31.580000+00:00
1  2014-02-14 09:16:14.237000+00:00  2019-11-02 00:01:47.617000+00:00
2  2014-01-03 09:18:13.003000+00:00  2018-05-25 08:41:47.910000+00:00
3  2017-04-18 08:19:03.827000+00:00  2017-04-18 11:06:41.550000+00:00
4  2020-04-16 17:00:55.503000+00:00  2022-09-22 07:43:50.933000+00:00

   owner_user_id  score  view_count  comment_count  answer_count  \
0        2310103     13        2874              5             1
1        1085703    129      177502              5             9
2        1420197     19       17665              7             5
3        2580955     80        6831              7             3
4        5942579     32       12260              2             5

     display_name              location
0  CanardMoussant       Antibes, France
1         dendini                   NaN
2    Ionică Bizău               Romania
3          s3rvac  Brno, Czech Republic
4  Emmanuel Mtali              Tanzania

In [9]:
#print(df.dtypes)
df['activity_length_mnths'] = ((pd.to_datetime(df.last_activity_date, format='mixed') - pd.to_datetime(df.creation_date, format='mixed')).dt.days / 30.4375).round(2)

print(df.head())

         id                                              title  \
0  52474162                  Why is SerialGC chosen over G1GC?
1  21775198     Facebook API "This app is in development mode"
2  20900218                  How to debug @font-face problems?
3  43467095  Why is a const variable sometimes not required...
4  61255807       Coroutine scope on Application class android

                      creation_date                last_activity_date  \
0  2018-09-24 07:03:09.697000+00:00  2022-05-01 15:01:31.580000+00:00
1  2014-02-14 09:16:14.237000+00:00  2019-11-02 00:01:47.617000+00:00
2  2014-01-03 09:18:13.003000+00:00  2018-05-25 08:41:47.910000+00:00
3  2017-04-18 08:19:03.827000+00:00  2017-04-18 11:06:41.550000+00:00
4  2020-04-16 17:00:55.503000+00:00  2022-09-22 07:43:50.933000+00:00

   owner_user_id  score  view_count  comment_count  answer_count  \
0        2310103     13        2874              5             1
1        1085703    129      177502              5             9
2        1420197     19       17665              7             5
3        2580955     80        6831              7             3
4        5942579     32       12260              2             5

     display_name              location  activity_length_mnths
0  CanardMoussant       Antibes, France                  43.20
1         dendini                   NaN                  68.53
2    Ionică Bizău               Romania                  52.63
3          s3rvac  Brno, Czech Republic                   0.00
4  Emmanuel Mtali              Tanzania                  29.17

In [10]:
t = df[['id','activity_length_mnths','comment_count','view_count','score','owner_user_id','display_name','location']]
print(t)

                id  activity_length_mnths  comment_count  view_count  score  \
0         52474162                  43.20              5        2874     13
1         21775198                  68.53              5      177502    129
2         20900218                  52.63              7       17665     19
3         43467095                   0.00              7        6831     80
4         61255807                  29.17              2       12260     32
...            ...                    ...            ...         ...    ...
22562255  27912483                   0.00              0        2197      8
22562256  10219571                  71.69              0        1508      8
22562257   5236636                   0.59              0        4583      8
22562258  71433130                   0.00              0         166      8
22562259  24515729                   1.77              0        2836      8

          owner_user_id    display_name  \
0               2310103  CanardMoussant
1               1085703         dendini
2               1420197    Ionică Bizău
3               2580955          s3rvac
4               5942579  Emmanuel Mtali
...                 ...             ...
22562255        2423425      Benkevitch
22562256         546509     Ethan Allen
22562257          41619    Adam Paynter
22562258       15475302      Yanyu Peng
22562259        1046810       Code Poet

                                                   location
0                                           Antibes, France
1                                                       NaN
2                                                   Romania
3                                      Brno, Czech Republic
4                                                  Tanzania
...                                                     ...
22562255  Massachusetts Institute of Technology, Haystac...
22562256                                     Windermere, FL
22562257                                          Plano, TX
22562258                                                NaN
22562259                                                NaN

[22562260 rows x 8 columns]

In [11]:
t.activity_length_mnths.describe()

count    2.256226e+07
mean     7.273281e+00
std      2.020375e+01
min     -3.000000e-02
25%      0.000000e+00
50%      0.000000e+00
75%      3.000000e-01
max      1.696600e+02
Name: activity_length_mnths, dtype: float64

In [12]:
t[['activity_length_mnths', 'score', 'view_count', 'comment_count']].corr()

,activity_length_mnths,score,view_count,comment_count
activity_length_mnths,1.000000,0.224210,0.295382,-0.026567
score,0.224210,1.000000,0.755065,0.011255
view_count,0.295382,0.755065,1.000000,0.007990
comment_count,-0.026567,0.011255,0.007990,1.000000

In [13]:
r = t[['id','activity_length_mnths', 'view_count', 'comment_count']]
r

                id  activity_length_mnths  view_count  comment_count
0         52474162                  43.20        2874              5
1         21775198                  68.53      177502              5
2         20900218                  52.63       17665              7
3         43467095                   0.00        6831              7
4         61255807                  29.17       12260              2
...            ...                    ...         ...            ...
22562255  27912483                   0.00        2197              0
22562256  10219571                  71.69        1508              0
22562257   5236636                   0.59        4583              0
22562258  71433130                   0.00         166              0
22562259  24515729                   1.77        2836              0

[22562260 rows x 4 columns]

In [14]:
r.count()

id                       22562260
activity_length_mnths    22562260
view_count               22562260
comment_count            22562260
dtype: int64

In [15]:
r.to_csv('/Users/noahgomez/GitHub/Analytics-Portfolio/stackoverflow_analysis/data/processed/active_posts.csv', index=False)
print(df.shape)

(22562260, 12)